apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: atask1
spec:
  steps:
  - name: task-one-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..10}; do echo GONLOGGIN 1 && sleep 3; done;'] # tests that targetpath works
  - name: task-one-step-two
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..10}; do echo GONLOGGIN 2 && sleep 3; done;'] 
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: emptylogs
spec:
  steps:
  - name: emptylogs-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..10}; do sleep 3; done;']
  - name: emptylogs-step-two
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..10}; do sleep 3; done;'] 
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task4
spec:
  inputs:
    params:
    - name: repository-url
    - name: repository-name
    - name: branch
  steps:
  - name: echo
    image: ubuntu
    command:
    - "/bin/bash"
    - "-c"
    args:
    - 'echo "Starting CICD pipeline for ''$(inputs.params.repository-name)'' from
      ''$(inputs.params.repository-url):$(inputs.params.branch)''"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task5
spec:
  steps:
  - name: task5step1
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 1 && sleep 3; done;'] # tests that targetpath works
  - name: task5step2
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 2 && sleep 3; done;'] 
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: bbtask7
spec:
  steps:
  - name: task7step1
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 1 && sleep 3; done;'] # tests that targetpath works
  - name: task7step2
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 2 && sleep 3; done;']
  - name: task7step3
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 2 && sleep 3; done;']
  - name: task7step4
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 2 && sleep 3; done;']
  - name: task7step5
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..3}; do echo GONLOGGIN 2 && sleep 3; done;'] 
