apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: 999-working-logs-long
spec:
  params:
    - name: repository-name
    - name: repository-url
    - name: branch
  tasks:
  - name: atask1
    taskRef:
      name: atask1
  - name: emptylogs
    taskRef:
      name: emptylogs
  - name: task2
    taskRef:
      name: task2
  - name: task3
    taskRef:
      name: task3
  - name: task4
    taskRef:
      name: task4
    params:
      - name: branch
        value: $(params.branch)
      - name: repository-name
        value: $(params.repository-name)
      - name: repository-url
        value: $(params.repository-url)
  - name: task5-somethingelse
    taskRef:
      name: task5
  - name: task6
    taskRef:
      name: task6
  - name: bbtask7
    taskRef:
      name: bbtask7
