apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: ubuntu
      command: ["/bin/bash"]
      args: ['-c', 'for i in {1..20}; do echo logging 1 && sleep 2; done;']
    - name: task-one-step-two
      image: ubuntu
      command: ['bash']
      args: ['-c', 'for i in {1..20}; do echo logging 2 && sleep 2; done;']
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task2
spec:
  steps:
    - name: task-two-step-one
      image: ubuntu
      command: ["/bin/bash"]
      args: ['-c', 'for i in {1..3}; do echo logging 1 && sleep 3; done;'] # tests that targetpath works
    - name: task2step-two
      image: ubuntu
      command: ['bash']
      args: ['-c', 'for i in {1..3}; do echo logging 2 && sleep 3; done;']
    - name: task-two-tep-three
      image: ubuntu
      command: ["/bin/bash"]
      args: ['-c', 'for i in {1..3}; do echo logging 1 && sleep 3; done;'] # tests that targetpath works
    - name: task-two-step-four
      image: ubuntu
      command: ['bash']
      args: ['-c', 'for i in {1..3}; do echo logging 2 && sleep 3; done;']