apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-two-step-one
      image: ubuntu
      command: ["/bin/bash"]
      args: ['-c', 'echo task 1 step 1;']
    - name: task2step-two
      image: ubuntu
      command: ['bash']
      args: ['-c', 'echo task 1 step 2;']
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task2
spec:
  steps:
    - name: task-two-step-one
      image: ubuntu
      command: ["/bin/bash"]
      args: ['-c', 'echo task 2 step 1;']
    - name: task2step-two
      image: ubuntu
      command: ['bash']
      args: ['-c', 'echo task 2 step 2;']